credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: User
      logged_in: false
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW  # "abc"
cookie:
  expiry_days: 30
  key: random_signature_key
  name: tma_auth_cookie
preauthorized:
  emails: []
